docker-build:
  image: skimia/docker-make:latest
  services:
    - docker:dind
  before_script:
    - docker info
    - make pull
  script:
    - make build
    - make test
    - make tag
    - docker image ls
    - docker login --username="${DOCKER_HUB_USERNAME}" --password="${DOCKER_HUB_PASSWORD}" && make push
  only:
    - master
